spring:
  application:
    name: tcc-zuul

server:
  port: 803

eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:802/eureka/

#设置超时时间
hystrix:
  command:
    default:
      execution:
        timeout:
          enabled: true
        isolation:
          thread:
            timeoutInMilliseconds: 60000

zuul:
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000
  ignored-services: '*'   # 使用'*'忽略所有微服务
  routes: # 路由白名单
    tcc-out: /out/** # http://localhost/user/api/** 转发到 tcc-out 下的 /api/**

ribbon:
  ReadTimeout: 60000  # 单位毫秒数
  SocketTimeout: 60000